site_name: My Docs

theme:
  name: material

nav:
  - US: 
    - Employment: US\employment.md
    - Consumption : US\consumption.md
    - Inflation : US\inflation.md
    - Business : US\business.md
  
  - Canada:
    - Employment: Canada\employment.md
    - Inflation : Canada\inflation.md
    - Business : Canada\business.md

  - Market: 
    - Sentiment: Market Sentiments\sentiment.md
    - Security Analysis: Market Sentiments\securities.md
  
  - Iran Conflict: theme\iran.md

markdown_extensions:
  - md_in_html

extra_javascript:
  - https://cdn.plot.ly/plotly-latest.min.js